### ISSUE TITLE
Print in JS?

### ISSUE THREAD

**Issue by rsxdalv** [spywhere/vscode-express-lines#1]
In the examples I can see printing code/unescaped strings via python print, however, using JavaScript console.log results in empty string.

I.e, I had 
<sel> =a b c
"<sel>".split(" ").join("_")
and I wanted to get a_b_c

**Comment by spywhere** [comment]
You don't have to use `console.log` as the expression will evaluated to string. Just think of it like a REPL in which you write an expression and the result will be used for target value.

The reason why Python need printing is because VSCode cannot run Python hence the extension need to run the script in the separate process in which the result will dump from that particular process.

**Comment by rsxdalv** [comment]
The core issue I have is escaped characters, i.e, in the a b c example say I wanted to get a newline for each space, but instead I'll get the escaped string: "a\nb\nc". In REPL I have access to stdout so I can just log these and copy the resulting string, but it can only be done via console.log

**Comment by spywhere** [comment]
Ah, got it. I'll mark this as an enhancement though, as the possible solution would be create a new evaluator just for this kind of issue.

**Comment by spywhere** [comment]
Meanwhile, you can add a new evaluator as followed...

```
{
    "identifier": "node",
    "name": "Node",
    "description": "Evaluate JavaScript expression using \"node\"",
    "command": [
        "node",
        "-e",
        "<expression>"
    ]
}
```

**Comment by rsxdalv** [comment]
I used this to also require ramda (similar to lodash). This is tool is unparalleled
